name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py38_0
  - astunparse=1.6.3=py_0
  - backcall=0.2.0=py_0
  - blas=1.0=mkl
  - blinker=1.4=py38_0
  - brotlipy=0.7.0=py38h7b6447c_1000
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.7.22=0
  - cachetools=4.1.1=py_0
  - certifi=2020.6.20=py38_0
  - cffi=1.14.1=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - click=7.1.2=py_0
  - cloudpickle=1.5.0=py_0
  - cryptography=2.9.2=py38h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py38_0
  - cytoolz=0.10.1=py38h7b6447c_0
  - dask-core=2.23.0=py_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - expat=2.2.9=he6710b0_2
  - fftw=3.3.8=nompi_h7f3a6c3_1111
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - gast=0.3.3=py_0
  - glib=2.65.0=h3eb4bd4_0
  - google-auth=1.20.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - grpcio=1.31.0=py38hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=nompi_py38h513d04c_102
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - imageio=2.9.0=py_0
  - importlib-metadata=1.7.0=py38_0
  - intel-openmp=2020.1=217
  - ipython=7.16.1=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - jedi=0.17.0=py38_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py38hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libitk=4.13.2=h8f2a977_6
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.4=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_1
  - markdown=3.2.2=py38_0
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38h817c723_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py38he904b0f_0
  - mkl_fft=1.1.0=py38h23d657b_0
  - mkl_random=1.1.1=py38h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - networkx=2.4=py_1
  - nibabel=3.1.1=py_0
  - numpy=1.19.1=py38hbc911f0_0
  - numpy-base=1.19.1=py38hfa32c7d_0
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py_0
  - openssl=1.1.1h=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandas=1.1.3=py38he6710b0_0
  - parso=0.8.0=py_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py38_0
  - pickleshare=0.7.5=py38_1000
  - pillow=7.2.0=py38hb39fc2d_0
  - pip=20.2.2=py38_0
  - prompt-toolkit=3.0.5=py_0
  - protobuf=3.12.4=py38he6710b0_0
  - ptyprocess=0.6.0=py38_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_2
  - pydicom=2.0.0=pyh9f0ad1d_0
  - pygments=2.6.1=py_0
  - pyjwt=1.7.1=py38_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38_0
  - python=3.8.5=hcff3b4d_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - pytz=2020.1=py_0
  - pywavelets=1.1.1=py38h7b6447c_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.6=py_0
  - scikit-image=0.16.2=py38h0573a6f_0
  - scikit-learn=0.23.1=py38h423224d_0
  - scipy=1.5.0=py38h0b6359f_0
  - setuptools=49.6.0=py38_0
  - simpleitk=1.2.4=py38h950e882_1
  - sip=4.19.13=py38he6710b0_0
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=2.2.1=pyh532a8cf_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.2.0=gpu_py38hb782248_0
  - tensorflow-base=2.2.0=gpu_py38h83e3d50_0
  - tensorflow-estimator=2.2.0=pyh208ff02_0
  - tensorflow-gpu=2.2.0=h0d30ee6_0
  - termcolor=1.1.0=py38_1
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.4=py38h7b6447c_1
  - tqdm=4.48.2=py_0
  - traitlets=4.3.3=py38_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - werkzeug=1.0.1=py_0
  - wheel=0.34.2=py38_0
  - wrapt=1.12.1=py38h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - tensorflow-addons==0.11.2
    - typeguard==2.9.1
prefix: /home/ubuntu/anaconda3/envs/tf2

